version: '2'
services:
  app.web:
    build:
      context: .
      args:
        env: prod
    ports:
      - "8081:80"
  app.web:
    build:
      contxt: .
      args:
        env:
    ports:
      - "5000:5000"